words = [
    "adsl",
    "datagram",
    "datagrams",
    "ebpf",
    "energie",
    "francesco",
    "maingau",
    "openwrt",
    "uhm",
    "vdsl",
    "winget",
]

# List of regex patterns to ignore when spell checking. Use single quotes for
# literal strings to avoid escaping backslashes.
ignore_patterns = [
    '^[A-Z]{2,}$',    # All caps words like "HTML", "CSS"
    'https?://[^\s]+' # URLs
]
