# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Documentation: https://www.mkdocs.org/user-guide/configuration/
site_name: Please wake me for code
site_url: https://pleasewakemeforco.de
theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - header.autohide
  favicon: assets/favicon.ico
  palette:
    # Documentation: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode

    # Palette for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2025 Francesco Zardi
extra:
  # Footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frazar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/francesco-zardi/

# Output folder where the static website is generated. Currently, GitHub pages only allows publishing either the root
# folder or the /docs folder.
site_dir: docs

# Input folder where Markdown-formatted articles and input assets are located
docs_dir: src

plugins:
  # Documentation: https://squidfunk.github.io/mkdocs-material/plugins/blog/
  - blog:
      blog_dir: .
      categories: false
      post_date_format: medium
      post_readtime: false

  # Documentation: https://guts.github.io/mkdocs-rss-plugin/
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

  ## Documentation: https://squidfunk.github.io/mkdocs-material/plugins/optimize/#general
  #- optimize:
  #      print_gain_summary: true

markdown_extensions:
  - abbr
  - attr_list
  - meta
  - pymdownx.blocks.caption
